greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: mysql
    username: sysprog
    password: S3cureP@ssw0rd!
    jdbc:
      url: jdbc:mysql://103.147.159.36:3306/hairisma_bank_demo?allowMultiQueries=true

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem


smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem


